version: 4.6.7
#preversion: 4.6-rc3
news:
  # enabled: true
  text: NLog 4.6.3 is live!
  readmore_text: Read more about 4.6
  readmore_link: https://nlog-project.org/2019/03/20/nlog-4-6-is-live.html
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
gems:
  - jekyll-redirect-from
  
