news:
  enabled: true
  text: NLog 5 is live!
  readmore_text: See new post
  readmore_link: https://nlog-project.org/2022/05/16/nlog-5-0-finally-ready.html
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
gems:
  - jekyll-redirect-from
  
